### ISSUE TITLE
allowPost not documented

### ISSUE THREAD

**Issue by sylvainlap** [vinialbano/passport-magic-link#3]
Hi,

Your README suggest to use a POST route to create a token, but this does not work out of the box.
After debugging your code, I saw the `allowPost` option, that is `undefied` by default.

You should set it to `true` by default, or at least document it.

Thanks !
Sylvain

**Comment by vinialbano** [comment]
Thanks @sylvainlap 
I have updated the source code and removed the `allowPost` parameter, accepting the `req.body` field by default.
