### ISSUE TITLE
create release for latest dependencies

### ISSUE THREAD

**Issue by matthew-cook-dxd** [vinialbano/passport-magic-link#34]
Current release fails `npm audit` due to vuln in `jsonwebtoken`. This is fixed by https://github.com/vinialbano/passport-magic-link/commit/4b361371a210ede62de53c5a8c79ddb4a52b1f14 but this commit is not included in a published release

**Comment by tongboh** [comment]
@matthew-cook-dxd A new release with the update has been published.
